multitenancy-platform:
  enabled: true
  tenants:
    - id: tenant_01
      name: tenant_01
      url: jdbc:mysql://localhost:3306/multitenancy_tenant_01?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: 123456
    - id: tenant_02
      name: tenant_02
      url: jdbc:mysql://localhost:3306/multitenancy_tenant_02?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: 123456
